// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module clicintv_reg (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [2:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        output clicintv_reg_pkg::clicintv__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [2:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[2:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic clicintv;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [2:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.clicintv = cpuif_req_masked & (cpuif_addr == 3'h0);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } v0;
            struct {
                logic [5:0] next;
                logic load_next;
            } vsid0;
            struct {
                logic next;
                logic load_next;
            } v1;
            struct {
                logic [5:0] next;
                logic load_next;
            } vsid1;
            struct {
                logic next;
                logic load_next;
            } v2;
            struct {
                logic [5:0] next;
                logic load_next;
            } vsid2;
            struct {
                logic next;
                logic load_next;
            } v3;
            struct {
                logic [5:0] next;
                logic load_next;
            } vsid3;
        } clicintv;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } v0;
            struct {
                logic [5:0] value;
            } vsid0;
            struct {
                logic value;
            } v1;
            struct {
                logic [5:0] value;
            } vsid1;
            struct {
                logic value;
            } v2;
            struct {
                logic [5:0] value;
            } vsid2;
            struct {
                logic value;
            } v3;
            struct {
                logic [5:0] value;
            } vsid3;
        } clicintv;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: clicintv.clicintv.v0
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.v0.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.v0.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.clicintv.v0.next = next_c;
        field_combo.clicintv.v0.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.v0.value <= 1'h0;
        end else begin
            if(field_combo.clicintv.v0.load_next) begin
                field_storage.clicintv.v0.value <= field_combo.clicintv.v0.next;
            end
        end
    end
    assign hwif_out.clicintv.v0.value = field_storage.clicintv.v0.value;
    // Field: clicintv.clicintv.vsid0
    always_comb begin
        automatic logic [5:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.vsid0.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.vsid0.value & ~decoded_wr_biten[7:2]) | (decoded_wr_data[7:2] & decoded_wr_biten[7:2]);
            load_next_c = '1;
        end
        field_combo.clicintv.vsid0.next = next_c;
        field_combo.clicintv.vsid0.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.vsid0.value <= 6'h0;
        end else begin
            if(field_combo.clicintv.vsid0.load_next) begin
                field_storage.clicintv.vsid0.value <= field_combo.clicintv.vsid0.next;
            end
        end
    end
    assign hwif_out.clicintv.vsid0.value = field_storage.clicintv.vsid0.value;
    // Field: clicintv.clicintv.v1
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.v1.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.v1.value & ~decoded_wr_biten[8:8]) | (decoded_wr_data[8:8] & decoded_wr_biten[8:8]);
            load_next_c = '1;
        end
        field_combo.clicintv.v1.next = next_c;
        field_combo.clicintv.v1.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.v1.value <= 1'h0;
        end else begin
            if(field_combo.clicintv.v1.load_next) begin
                field_storage.clicintv.v1.value <= field_combo.clicintv.v1.next;
            end
        end
    end
    assign hwif_out.clicintv.v1.value = field_storage.clicintv.v1.value;
    // Field: clicintv.clicintv.vsid1
    always_comb begin
        automatic logic [5:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.vsid1.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.vsid1.value & ~decoded_wr_biten[15:10]) | (decoded_wr_data[15:10] & decoded_wr_biten[15:10]);
            load_next_c = '1;
        end
        field_combo.clicintv.vsid1.next = next_c;
        field_combo.clicintv.vsid1.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.vsid1.value <= 6'h0;
        end else begin
            if(field_combo.clicintv.vsid1.load_next) begin
                field_storage.clicintv.vsid1.value <= field_combo.clicintv.vsid1.next;
            end
        end
    end
    assign hwif_out.clicintv.vsid1.value = field_storage.clicintv.vsid1.value;
    // Field: clicintv.clicintv.v2
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.v2.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.v2.value & ~decoded_wr_biten[16:16]) | (decoded_wr_data[16:16] & decoded_wr_biten[16:16]);
            load_next_c = '1;
        end
        field_combo.clicintv.v2.next = next_c;
        field_combo.clicintv.v2.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.v2.value <= 1'h0;
        end else begin
            if(field_combo.clicintv.v2.load_next) begin
                field_storage.clicintv.v2.value <= field_combo.clicintv.v2.next;
            end
        end
    end
    assign hwif_out.clicintv.v2.value = field_storage.clicintv.v2.value;
    // Field: clicintv.clicintv.vsid2
    always_comb begin
        automatic logic [5:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.vsid2.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.vsid2.value & ~decoded_wr_biten[23:18]) | (decoded_wr_data[23:18] & decoded_wr_biten[23:18]);
            load_next_c = '1;
        end
        field_combo.clicintv.vsid2.next = next_c;
        field_combo.clicintv.vsid2.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.vsid2.value <= 6'h0;
        end else begin
            if(field_combo.clicintv.vsid2.load_next) begin
                field_storage.clicintv.vsid2.value <= field_combo.clicintv.vsid2.next;
            end
        end
    end
    assign hwif_out.clicintv.vsid2.value = field_storage.clicintv.vsid2.value;
    // Field: clicintv.clicintv.v3
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.v3.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.v3.value & ~decoded_wr_biten[24:24]) | (decoded_wr_data[24:24] & decoded_wr_biten[24:24]);
            load_next_c = '1;
        end
        field_combo.clicintv.v3.next = next_c;
        field_combo.clicintv.v3.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.v3.value <= 1'h0;
        end else begin
            if(field_combo.clicintv.v3.load_next) begin
                field_storage.clicintv.v3.value <= field_combo.clicintv.v3.next;
            end
        end
    end
    assign hwif_out.clicintv.v3.value = field_storage.clicintv.v3.value;
    // Field: clicintv.clicintv.vsid3
    always_comb begin
        automatic logic [5:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicintv.vsid3.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicintv && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicintv.vsid3.value & ~decoded_wr_biten[31:26]) | (decoded_wr_data[31:26] & decoded_wr_biten[31:26]);
            load_next_c = '1;
        end
        field_combo.clicintv.vsid3.next = next_c;
        field_combo.clicintv.vsid3.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicintv.vsid3.value <= 6'h0;
        end else begin
            if(field_combo.clicintv.vsid3.load_next) begin
                field_storage.clicintv.vsid3.value <= field_combo.clicintv.vsid3.next;
            end
        end
    end
    assign hwif_out.clicintv.vsid3.value = field_storage.clicintv.vsid3.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [2:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 3'h0) begin
            readback_data_var[0] = field_storage.clicintv.v0.value;
            readback_data_var[7:2] = field_storage.clicintv.vsid0.value;
            readback_data_var[8] = field_storage.clicintv.v1.value;
            readback_data_var[15:10] = field_storage.clicintv.vsid1.value;
            readback_data_var[16] = field_storage.clicintv.v2.value;
            readback_data_var[23:18] = field_storage.clicintv.vsid2.value;
            readback_data_var[24] = field_storage.clicintv.v3.value;
            readback_data_var[31:26] = field_storage.clicintv.vsid3.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
