// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package clicint_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } ip;
    struct packed {
      logic        q;
    } ie;
    struct packed {
      logic        q;
    } attr_shv;
    struct packed {
      logic [1:0]  q;
    } attr_trig;
    struct packed {
      logic [1:0]  q;
    } attr_mode;
    struct packed {
      logic [7:0]  q;
    } ctl;
  } clicint_reg2hw_clicint_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } ip;
  } clicint_hw2reg_clicint_reg_t;

  // Register -> HW type
  typedef struct packed {
    clicint_reg2hw_clicint_reg_t clicint; // [14:0]
  } clicint_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    clicint_hw2reg_clicint_reg_t clicint; // [1:0]
  } clicint_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CLICINT_CLICINT_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    CLICINT_CLICINT
  } clicint_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CLICINT_PERMIT [1] = '{
    4'b 1111  // index[0] CLICINT_CLICINT
  };

endpackage

