// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package clicint_reg_pkg;

    localparam CLICINT_REG_DATA_WIDTH = 32;
    localparam CLICINT_REG_MIN_ADDR_WIDTH = 3;
    localparam CLICINT_REG_SIZE = 'h4;

    typedef struct {
        logic next;
        logic we;
    } clicint_t__ip__in_t;

    typedef struct {
        clicint_t__ip__in_t ip;
    } clicint_t__in_t;

    typedef struct {
        clicint_t__in_t clicint;
    } clicint__in_t;

    typedef struct {
        logic value;
    } clicint_t__ip__out_t;

    typedef struct {
        logic value;
    } clicint_t__ie__out_t;

    typedef struct {
        logic value;
    } clicint_t__attr_shv__out_t;

    typedef struct {
        logic [1:0] value;
    } clicint_t__attr_trig__out_t;

    typedef struct {
        logic [1:0] value;
    } clicint_t__attr_mode__out_t;

    typedef struct {
        logic [7:0] value;
    } clicint_t__ctl__out_t;

    typedef struct {
        clicint_t__ip__out_t ip;
        clicint_t__ie__out_t ie;
        clicint_t__attr_shv__out_t attr_shv;
        clicint_t__attr_trig__out_t attr_trig;
        clicint_t__attr_mode__out_t attr_mode;
        clicint_t__ctl__out_t ctl;
    } clicint_t__out_t;

    typedef struct {
        clicint_t__out_t clicint;
    } clicint__out_t;
endpackage
