// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package clic_reg_pkg;

  // Param list
  parameter int NumSrc = 256;
  parameter int ClicIntCtlBits = 8;

  // Address widths within the block
  parameter int BlockAw = 13;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } nvbits;
    struct packed {
      logic [3:0]  q;
    } nlbits;
    struct packed {
      logic [1:0]  q;
    } nmbits;
  } clic_reg2hw_cliccfg_reg_t;

  typedef struct packed {
    struct packed {
      logic [12:0] q;
    } num_interrupt;
    struct packed {
      logic [7:0]  q;
    } version;
    struct packed {
      logic [3:0]  q;
    } clicintctlbits;
    struct packed {
      logic [5:0]  q;
    } num_trigger;
  } clic_reg2hw_clicinfo_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } ip;
    struct packed {
      logic        q;
    } ie;
    struct packed {
      logic        q;
    } attr_shv;
    struct packed {
      logic [1:0]  q;
    } attr_trig;
    struct packed {
      logic [1:0]  q;
    } attr_mode;
    struct packed {
      logic [7:0]  q;
    } ctl;
  } clic_reg2hw_clicint_mreg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } ip;
  } clic_hw2reg_clicint_mreg_t;

  // Register -> HW type
  typedef struct packed {
    clic_reg2hw_cliccfg_reg_t cliccfg; // [3877:3871]
    clic_reg2hw_clicinfo_reg_t clicinfo; // [3870:3840]
    clic_reg2hw_clicint_mreg_t [255:0] clicint; // [3839:0]
  } clic_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    clic_hw2reg_clicint_mreg_t [255:0] clicint; // [511:0]
  } clic_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CLIC_CLICCFG_OFFSET = 13'h 0;
  parameter logic [BlockAw-1:0] CLIC_CLICINFO_OFFSET = 13'h 4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_0_OFFSET = 13'h 1000;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_1_OFFSET = 13'h 1004;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_2_OFFSET = 13'h 1008;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_3_OFFSET = 13'h 100c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_4_OFFSET = 13'h 1010;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_5_OFFSET = 13'h 1014;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_6_OFFSET = 13'h 1018;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_7_OFFSET = 13'h 101c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_8_OFFSET = 13'h 1020;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_9_OFFSET = 13'h 1024;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_10_OFFSET = 13'h 1028;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_11_OFFSET = 13'h 102c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_12_OFFSET = 13'h 1030;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_13_OFFSET = 13'h 1034;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_14_OFFSET = 13'h 1038;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_15_OFFSET = 13'h 103c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_16_OFFSET = 13'h 1040;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_17_OFFSET = 13'h 1044;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_18_OFFSET = 13'h 1048;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_19_OFFSET = 13'h 104c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_20_OFFSET = 13'h 1050;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_21_OFFSET = 13'h 1054;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_22_OFFSET = 13'h 1058;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_23_OFFSET = 13'h 105c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_24_OFFSET = 13'h 1060;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_25_OFFSET = 13'h 1064;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_26_OFFSET = 13'h 1068;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_27_OFFSET = 13'h 106c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_28_OFFSET = 13'h 1070;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_29_OFFSET = 13'h 1074;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_30_OFFSET = 13'h 1078;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_31_OFFSET = 13'h 107c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_32_OFFSET = 13'h 1080;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_33_OFFSET = 13'h 1084;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_34_OFFSET = 13'h 1088;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_35_OFFSET = 13'h 108c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_36_OFFSET = 13'h 1090;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_37_OFFSET = 13'h 1094;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_38_OFFSET = 13'h 1098;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_39_OFFSET = 13'h 109c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_40_OFFSET = 13'h 10a0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_41_OFFSET = 13'h 10a4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_42_OFFSET = 13'h 10a8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_43_OFFSET = 13'h 10ac;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_44_OFFSET = 13'h 10b0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_45_OFFSET = 13'h 10b4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_46_OFFSET = 13'h 10b8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_47_OFFSET = 13'h 10bc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_48_OFFSET = 13'h 10c0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_49_OFFSET = 13'h 10c4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_50_OFFSET = 13'h 10c8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_51_OFFSET = 13'h 10cc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_52_OFFSET = 13'h 10d0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_53_OFFSET = 13'h 10d4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_54_OFFSET = 13'h 10d8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_55_OFFSET = 13'h 10dc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_56_OFFSET = 13'h 10e0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_57_OFFSET = 13'h 10e4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_58_OFFSET = 13'h 10e8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_59_OFFSET = 13'h 10ec;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_60_OFFSET = 13'h 10f0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_61_OFFSET = 13'h 10f4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_62_OFFSET = 13'h 10f8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_63_OFFSET = 13'h 10fc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_64_OFFSET = 13'h 1100;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_65_OFFSET = 13'h 1104;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_66_OFFSET = 13'h 1108;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_67_OFFSET = 13'h 110c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_68_OFFSET = 13'h 1110;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_69_OFFSET = 13'h 1114;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_70_OFFSET = 13'h 1118;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_71_OFFSET = 13'h 111c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_72_OFFSET = 13'h 1120;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_73_OFFSET = 13'h 1124;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_74_OFFSET = 13'h 1128;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_75_OFFSET = 13'h 112c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_76_OFFSET = 13'h 1130;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_77_OFFSET = 13'h 1134;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_78_OFFSET = 13'h 1138;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_79_OFFSET = 13'h 113c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_80_OFFSET = 13'h 1140;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_81_OFFSET = 13'h 1144;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_82_OFFSET = 13'h 1148;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_83_OFFSET = 13'h 114c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_84_OFFSET = 13'h 1150;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_85_OFFSET = 13'h 1154;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_86_OFFSET = 13'h 1158;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_87_OFFSET = 13'h 115c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_88_OFFSET = 13'h 1160;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_89_OFFSET = 13'h 1164;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_90_OFFSET = 13'h 1168;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_91_OFFSET = 13'h 116c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_92_OFFSET = 13'h 1170;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_93_OFFSET = 13'h 1174;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_94_OFFSET = 13'h 1178;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_95_OFFSET = 13'h 117c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_96_OFFSET = 13'h 1180;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_97_OFFSET = 13'h 1184;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_98_OFFSET = 13'h 1188;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_99_OFFSET = 13'h 118c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_100_OFFSET = 13'h 1190;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_101_OFFSET = 13'h 1194;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_102_OFFSET = 13'h 1198;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_103_OFFSET = 13'h 119c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_104_OFFSET = 13'h 11a0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_105_OFFSET = 13'h 11a4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_106_OFFSET = 13'h 11a8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_107_OFFSET = 13'h 11ac;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_108_OFFSET = 13'h 11b0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_109_OFFSET = 13'h 11b4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_110_OFFSET = 13'h 11b8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_111_OFFSET = 13'h 11bc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_112_OFFSET = 13'h 11c0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_113_OFFSET = 13'h 11c4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_114_OFFSET = 13'h 11c8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_115_OFFSET = 13'h 11cc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_116_OFFSET = 13'h 11d0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_117_OFFSET = 13'h 11d4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_118_OFFSET = 13'h 11d8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_119_OFFSET = 13'h 11dc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_120_OFFSET = 13'h 11e0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_121_OFFSET = 13'h 11e4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_122_OFFSET = 13'h 11e8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_123_OFFSET = 13'h 11ec;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_124_OFFSET = 13'h 11f0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_125_OFFSET = 13'h 11f4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_126_OFFSET = 13'h 11f8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_127_OFFSET = 13'h 11fc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_128_OFFSET = 13'h 1200;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_129_OFFSET = 13'h 1204;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_130_OFFSET = 13'h 1208;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_131_OFFSET = 13'h 120c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_132_OFFSET = 13'h 1210;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_133_OFFSET = 13'h 1214;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_134_OFFSET = 13'h 1218;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_135_OFFSET = 13'h 121c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_136_OFFSET = 13'h 1220;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_137_OFFSET = 13'h 1224;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_138_OFFSET = 13'h 1228;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_139_OFFSET = 13'h 122c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_140_OFFSET = 13'h 1230;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_141_OFFSET = 13'h 1234;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_142_OFFSET = 13'h 1238;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_143_OFFSET = 13'h 123c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_144_OFFSET = 13'h 1240;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_145_OFFSET = 13'h 1244;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_146_OFFSET = 13'h 1248;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_147_OFFSET = 13'h 124c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_148_OFFSET = 13'h 1250;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_149_OFFSET = 13'h 1254;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_150_OFFSET = 13'h 1258;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_151_OFFSET = 13'h 125c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_152_OFFSET = 13'h 1260;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_153_OFFSET = 13'h 1264;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_154_OFFSET = 13'h 1268;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_155_OFFSET = 13'h 126c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_156_OFFSET = 13'h 1270;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_157_OFFSET = 13'h 1274;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_158_OFFSET = 13'h 1278;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_159_OFFSET = 13'h 127c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_160_OFFSET = 13'h 1280;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_161_OFFSET = 13'h 1284;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_162_OFFSET = 13'h 1288;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_163_OFFSET = 13'h 128c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_164_OFFSET = 13'h 1290;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_165_OFFSET = 13'h 1294;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_166_OFFSET = 13'h 1298;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_167_OFFSET = 13'h 129c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_168_OFFSET = 13'h 12a0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_169_OFFSET = 13'h 12a4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_170_OFFSET = 13'h 12a8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_171_OFFSET = 13'h 12ac;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_172_OFFSET = 13'h 12b0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_173_OFFSET = 13'h 12b4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_174_OFFSET = 13'h 12b8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_175_OFFSET = 13'h 12bc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_176_OFFSET = 13'h 12c0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_177_OFFSET = 13'h 12c4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_178_OFFSET = 13'h 12c8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_179_OFFSET = 13'h 12cc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_180_OFFSET = 13'h 12d0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_181_OFFSET = 13'h 12d4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_182_OFFSET = 13'h 12d8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_183_OFFSET = 13'h 12dc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_184_OFFSET = 13'h 12e0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_185_OFFSET = 13'h 12e4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_186_OFFSET = 13'h 12e8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_187_OFFSET = 13'h 12ec;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_188_OFFSET = 13'h 12f0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_189_OFFSET = 13'h 12f4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_190_OFFSET = 13'h 12f8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_191_OFFSET = 13'h 12fc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_192_OFFSET = 13'h 1300;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_193_OFFSET = 13'h 1304;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_194_OFFSET = 13'h 1308;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_195_OFFSET = 13'h 130c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_196_OFFSET = 13'h 1310;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_197_OFFSET = 13'h 1314;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_198_OFFSET = 13'h 1318;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_199_OFFSET = 13'h 131c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_200_OFFSET = 13'h 1320;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_201_OFFSET = 13'h 1324;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_202_OFFSET = 13'h 1328;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_203_OFFSET = 13'h 132c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_204_OFFSET = 13'h 1330;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_205_OFFSET = 13'h 1334;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_206_OFFSET = 13'h 1338;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_207_OFFSET = 13'h 133c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_208_OFFSET = 13'h 1340;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_209_OFFSET = 13'h 1344;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_210_OFFSET = 13'h 1348;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_211_OFFSET = 13'h 134c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_212_OFFSET = 13'h 1350;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_213_OFFSET = 13'h 1354;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_214_OFFSET = 13'h 1358;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_215_OFFSET = 13'h 135c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_216_OFFSET = 13'h 1360;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_217_OFFSET = 13'h 1364;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_218_OFFSET = 13'h 1368;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_219_OFFSET = 13'h 136c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_220_OFFSET = 13'h 1370;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_221_OFFSET = 13'h 1374;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_222_OFFSET = 13'h 1378;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_223_OFFSET = 13'h 137c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_224_OFFSET = 13'h 1380;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_225_OFFSET = 13'h 1384;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_226_OFFSET = 13'h 1388;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_227_OFFSET = 13'h 138c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_228_OFFSET = 13'h 1390;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_229_OFFSET = 13'h 1394;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_230_OFFSET = 13'h 1398;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_231_OFFSET = 13'h 139c;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_232_OFFSET = 13'h 13a0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_233_OFFSET = 13'h 13a4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_234_OFFSET = 13'h 13a8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_235_OFFSET = 13'h 13ac;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_236_OFFSET = 13'h 13b0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_237_OFFSET = 13'h 13b4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_238_OFFSET = 13'h 13b8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_239_OFFSET = 13'h 13bc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_240_OFFSET = 13'h 13c0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_241_OFFSET = 13'h 13c4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_242_OFFSET = 13'h 13c8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_243_OFFSET = 13'h 13cc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_244_OFFSET = 13'h 13d0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_245_OFFSET = 13'h 13d4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_246_OFFSET = 13'h 13d8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_247_OFFSET = 13'h 13dc;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_248_OFFSET = 13'h 13e0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_249_OFFSET = 13'h 13e4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_250_OFFSET = 13'h 13e8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_251_OFFSET = 13'h 13ec;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_252_OFFSET = 13'h 13f0;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_253_OFFSET = 13'h 13f4;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_254_OFFSET = 13'h 13f8;
  parameter logic [BlockAw-1:0] CLIC_CLICINT_255_OFFSET = 13'h 13fc;

  // Register index
  typedef enum int {
    CLIC_CLICCFG,
    CLIC_CLICINFO,
    CLIC_CLICINT_0,
    CLIC_CLICINT_1,
    CLIC_CLICINT_2,
    CLIC_CLICINT_3,
    CLIC_CLICINT_4,
    CLIC_CLICINT_5,
    CLIC_CLICINT_6,
    CLIC_CLICINT_7,
    CLIC_CLICINT_8,
    CLIC_CLICINT_9,
    CLIC_CLICINT_10,
    CLIC_CLICINT_11,
    CLIC_CLICINT_12,
    CLIC_CLICINT_13,
    CLIC_CLICINT_14,
    CLIC_CLICINT_15,
    CLIC_CLICINT_16,
    CLIC_CLICINT_17,
    CLIC_CLICINT_18,
    CLIC_CLICINT_19,
    CLIC_CLICINT_20,
    CLIC_CLICINT_21,
    CLIC_CLICINT_22,
    CLIC_CLICINT_23,
    CLIC_CLICINT_24,
    CLIC_CLICINT_25,
    CLIC_CLICINT_26,
    CLIC_CLICINT_27,
    CLIC_CLICINT_28,
    CLIC_CLICINT_29,
    CLIC_CLICINT_30,
    CLIC_CLICINT_31,
    CLIC_CLICINT_32,
    CLIC_CLICINT_33,
    CLIC_CLICINT_34,
    CLIC_CLICINT_35,
    CLIC_CLICINT_36,
    CLIC_CLICINT_37,
    CLIC_CLICINT_38,
    CLIC_CLICINT_39,
    CLIC_CLICINT_40,
    CLIC_CLICINT_41,
    CLIC_CLICINT_42,
    CLIC_CLICINT_43,
    CLIC_CLICINT_44,
    CLIC_CLICINT_45,
    CLIC_CLICINT_46,
    CLIC_CLICINT_47,
    CLIC_CLICINT_48,
    CLIC_CLICINT_49,
    CLIC_CLICINT_50,
    CLIC_CLICINT_51,
    CLIC_CLICINT_52,
    CLIC_CLICINT_53,
    CLIC_CLICINT_54,
    CLIC_CLICINT_55,
    CLIC_CLICINT_56,
    CLIC_CLICINT_57,
    CLIC_CLICINT_58,
    CLIC_CLICINT_59,
    CLIC_CLICINT_60,
    CLIC_CLICINT_61,
    CLIC_CLICINT_62,
    CLIC_CLICINT_63,
    CLIC_CLICINT_64,
    CLIC_CLICINT_65,
    CLIC_CLICINT_66,
    CLIC_CLICINT_67,
    CLIC_CLICINT_68,
    CLIC_CLICINT_69,
    CLIC_CLICINT_70,
    CLIC_CLICINT_71,
    CLIC_CLICINT_72,
    CLIC_CLICINT_73,
    CLIC_CLICINT_74,
    CLIC_CLICINT_75,
    CLIC_CLICINT_76,
    CLIC_CLICINT_77,
    CLIC_CLICINT_78,
    CLIC_CLICINT_79,
    CLIC_CLICINT_80,
    CLIC_CLICINT_81,
    CLIC_CLICINT_82,
    CLIC_CLICINT_83,
    CLIC_CLICINT_84,
    CLIC_CLICINT_85,
    CLIC_CLICINT_86,
    CLIC_CLICINT_87,
    CLIC_CLICINT_88,
    CLIC_CLICINT_89,
    CLIC_CLICINT_90,
    CLIC_CLICINT_91,
    CLIC_CLICINT_92,
    CLIC_CLICINT_93,
    CLIC_CLICINT_94,
    CLIC_CLICINT_95,
    CLIC_CLICINT_96,
    CLIC_CLICINT_97,
    CLIC_CLICINT_98,
    CLIC_CLICINT_99,
    CLIC_CLICINT_100,
    CLIC_CLICINT_101,
    CLIC_CLICINT_102,
    CLIC_CLICINT_103,
    CLIC_CLICINT_104,
    CLIC_CLICINT_105,
    CLIC_CLICINT_106,
    CLIC_CLICINT_107,
    CLIC_CLICINT_108,
    CLIC_CLICINT_109,
    CLIC_CLICINT_110,
    CLIC_CLICINT_111,
    CLIC_CLICINT_112,
    CLIC_CLICINT_113,
    CLIC_CLICINT_114,
    CLIC_CLICINT_115,
    CLIC_CLICINT_116,
    CLIC_CLICINT_117,
    CLIC_CLICINT_118,
    CLIC_CLICINT_119,
    CLIC_CLICINT_120,
    CLIC_CLICINT_121,
    CLIC_CLICINT_122,
    CLIC_CLICINT_123,
    CLIC_CLICINT_124,
    CLIC_CLICINT_125,
    CLIC_CLICINT_126,
    CLIC_CLICINT_127,
    CLIC_CLICINT_128,
    CLIC_CLICINT_129,
    CLIC_CLICINT_130,
    CLIC_CLICINT_131,
    CLIC_CLICINT_132,
    CLIC_CLICINT_133,
    CLIC_CLICINT_134,
    CLIC_CLICINT_135,
    CLIC_CLICINT_136,
    CLIC_CLICINT_137,
    CLIC_CLICINT_138,
    CLIC_CLICINT_139,
    CLIC_CLICINT_140,
    CLIC_CLICINT_141,
    CLIC_CLICINT_142,
    CLIC_CLICINT_143,
    CLIC_CLICINT_144,
    CLIC_CLICINT_145,
    CLIC_CLICINT_146,
    CLIC_CLICINT_147,
    CLIC_CLICINT_148,
    CLIC_CLICINT_149,
    CLIC_CLICINT_150,
    CLIC_CLICINT_151,
    CLIC_CLICINT_152,
    CLIC_CLICINT_153,
    CLIC_CLICINT_154,
    CLIC_CLICINT_155,
    CLIC_CLICINT_156,
    CLIC_CLICINT_157,
    CLIC_CLICINT_158,
    CLIC_CLICINT_159,
    CLIC_CLICINT_160,
    CLIC_CLICINT_161,
    CLIC_CLICINT_162,
    CLIC_CLICINT_163,
    CLIC_CLICINT_164,
    CLIC_CLICINT_165,
    CLIC_CLICINT_166,
    CLIC_CLICINT_167,
    CLIC_CLICINT_168,
    CLIC_CLICINT_169,
    CLIC_CLICINT_170,
    CLIC_CLICINT_171,
    CLIC_CLICINT_172,
    CLIC_CLICINT_173,
    CLIC_CLICINT_174,
    CLIC_CLICINT_175,
    CLIC_CLICINT_176,
    CLIC_CLICINT_177,
    CLIC_CLICINT_178,
    CLIC_CLICINT_179,
    CLIC_CLICINT_180,
    CLIC_CLICINT_181,
    CLIC_CLICINT_182,
    CLIC_CLICINT_183,
    CLIC_CLICINT_184,
    CLIC_CLICINT_185,
    CLIC_CLICINT_186,
    CLIC_CLICINT_187,
    CLIC_CLICINT_188,
    CLIC_CLICINT_189,
    CLIC_CLICINT_190,
    CLIC_CLICINT_191,
    CLIC_CLICINT_192,
    CLIC_CLICINT_193,
    CLIC_CLICINT_194,
    CLIC_CLICINT_195,
    CLIC_CLICINT_196,
    CLIC_CLICINT_197,
    CLIC_CLICINT_198,
    CLIC_CLICINT_199,
    CLIC_CLICINT_200,
    CLIC_CLICINT_201,
    CLIC_CLICINT_202,
    CLIC_CLICINT_203,
    CLIC_CLICINT_204,
    CLIC_CLICINT_205,
    CLIC_CLICINT_206,
    CLIC_CLICINT_207,
    CLIC_CLICINT_208,
    CLIC_CLICINT_209,
    CLIC_CLICINT_210,
    CLIC_CLICINT_211,
    CLIC_CLICINT_212,
    CLIC_CLICINT_213,
    CLIC_CLICINT_214,
    CLIC_CLICINT_215,
    CLIC_CLICINT_216,
    CLIC_CLICINT_217,
    CLIC_CLICINT_218,
    CLIC_CLICINT_219,
    CLIC_CLICINT_220,
    CLIC_CLICINT_221,
    CLIC_CLICINT_222,
    CLIC_CLICINT_223,
    CLIC_CLICINT_224,
    CLIC_CLICINT_225,
    CLIC_CLICINT_226,
    CLIC_CLICINT_227,
    CLIC_CLICINT_228,
    CLIC_CLICINT_229,
    CLIC_CLICINT_230,
    CLIC_CLICINT_231,
    CLIC_CLICINT_232,
    CLIC_CLICINT_233,
    CLIC_CLICINT_234,
    CLIC_CLICINT_235,
    CLIC_CLICINT_236,
    CLIC_CLICINT_237,
    CLIC_CLICINT_238,
    CLIC_CLICINT_239,
    CLIC_CLICINT_240,
    CLIC_CLICINT_241,
    CLIC_CLICINT_242,
    CLIC_CLICINT_243,
    CLIC_CLICINT_244,
    CLIC_CLICINT_245,
    CLIC_CLICINT_246,
    CLIC_CLICINT_247,
    CLIC_CLICINT_248,
    CLIC_CLICINT_249,
    CLIC_CLICINT_250,
    CLIC_CLICINT_251,
    CLIC_CLICINT_252,
    CLIC_CLICINT_253,
    CLIC_CLICINT_254,
    CLIC_CLICINT_255
  } clic_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CLIC_PERMIT [258] = '{
    4'b 1111, // index[  0] CLIC_CLICCFG
    4'b 1111, // index[  1] CLIC_CLICINFO
    4'b 1111, // index[  2] CLIC_CLICINT_0
    4'b 1111, // index[  3] CLIC_CLICINT_1
    4'b 1111, // index[  4] CLIC_CLICINT_2
    4'b 1111, // index[  5] CLIC_CLICINT_3
    4'b 1111, // index[  6] CLIC_CLICINT_4
    4'b 1111, // index[  7] CLIC_CLICINT_5
    4'b 1111, // index[  8] CLIC_CLICINT_6
    4'b 1111, // index[  9] CLIC_CLICINT_7
    4'b 1111, // index[ 10] CLIC_CLICINT_8
    4'b 1111, // index[ 11] CLIC_CLICINT_9
    4'b 1111, // index[ 12] CLIC_CLICINT_10
    4'b 1111, // index[ 13] CLIC_CLICINT_11
    4'b 1111, // index[ 14] CLIC_CLICINT_12
    4'b 1111, // index[ 15] CLIC_CLICINT_13
    4'b 1111, // index[ 16] CLIC_CLICINT_14
    4'b 1111, // index[ 17] CLIC_CLICINT_15
    4'b 1111, // index[ 18] CLIC_CLICINT_16
    4'b 1111, // index[ 19] CLIC_CLICINT_17
    4'b 1111, // index[ 20] CLIC_CLICINT_18
    4'b 1111, // index[ 21] CLIC_CLICINT_19
    4'b 1111, // index[ 22] CLIC_CLICINT_20
    4'b 1111, // index[ 23] CLIC_CLICINT_21
    4'b 1111, // index[ 24] CLIC_CLICINT_22
    4'b 1111, // index[ 25] CLIC_CLICINT_23
    4'b 1111, // index[ 26] CLIC_CLICINT_24
    4'b 1111, // index[ 27] CLIC_CLICINT_25
    4'b 1111, // index[ 28] CLIC_CLICINT_26
    4'b 1111, // index[ 29] CLIC_CLICINT_27
    4'b 1111, // index[ 30] CLIC_CLICINT_28
    4'b 1111, // index[ 31] CLIC_CLICINT_29
    4'b 1111, // index[ 32] CLIC_CLICINT_30
    4'b 1111, // index[ 33] CLIC_CLICINT_31
    4'b 1111, // index[ 34] CLIC_CLICINT_32
    4'b 1111, // index[ 35] CLIC_CLICINT_33
    4'b 1111, // index[ 36] CLIC_CLICINT_34
    4'b 1111, // index[ 37] CLIC_CLICINT_35
    4'b 1111, // index[ 38] CLIC_CLICINT_36
    4'b 1111, // index[ 39] CLIC_CLICINT_37
    4'b 1111, // index[ 40] CLIC_CLICINT_38
    4'b 1111, // index[ 41] CLIC_CLICINT_39
    4'b 1111, // index[ 42] CLIC_CLICINT_40
    4'b 1111, // index[ 43] CLIC_CLICINT_41
    4'b 1111, // index[ 44] CLIC_CLICINT_42
    4'b 1111, // index[ 45] CLIC_CLICINT_43
    4'b 1111, // index[ 46] CLIC_CLICINT_44
    4'b 1111, // index[ 47] CLIC_CLICINT_45
    4'b 1111, // index[ 48] CLIC_CLICINT_46
    4'b 1111, // index[ 49] CLIC_CLICINT_47
    4'b 1111, // index[ 50] CLIC_CLICINT_48
    4'b 1111, // index[ 51] CLIC_CLICINT_49
    4'b 1111, // index[ 52] CLIC_CLICINT_50
    4'b 1111, // index[ 53] CLIC_CLICINT_51
    4'b 1111, // index[ 54] CLIC_CLICINT_52
    4'b 1111, // index[ 55] CLIC_CLICINT_53
    4'b 1111, // index[ 56] CLIC_CLICINT_54
    4'b 1111, // index[ 57] CLIC_CLICINT_55
    4'b 1111, // index[ 58] CLIC_CLICINT_56
    4'b 1111, // index[ 59] CLIC_CLICINT_57
    4'b 1111, // index[ 60] CLIC_CLICINT_58
    4'b 1111, // index[ 61] CLIC_CLICINT_59
    4'b 1111, // index[ 62] CLIC_CLICINT_60
    4'b 1111, // index[ 63] CLIC_CLICINT_61
    4'b 1111, // index[ 64] CLIC_CLICINT_62
    4'b 1111, // index[ 65] CLIC_CLICINT_63
    4'b 1111, // index[ 66] CLIC_CLICINT_64
    4'b 1111, // index[ 67] CLIC_CLICINT_65
    4'b 1111, // index[ 68] CLIC_CLICINT_66
    4'b 1111, // index[ 69] CLIC_CLICINT_67
    4'b 1111, // index[ 70] CLIC_CLICINT_68
    4'b 1111, // index[ 71] CLIC_CLICINT_69
    4'b 1111, // index[ 72] CLIC_CLICINT_70
    4'b 1111, // index[ 73] CLIC_CLICINT_71
    4'b 1111, // index[ 74] CLIC_CLICINT_72
    4'b 1111, // index[ 75] CLIC_CLICINT_73
    4'b 1111, // index[ 76] CLIC_CLICINT_74
    4'b 1111, // index[ 77] CLIC_CLICINT_75
    4'b 1111, // index[ 78] CLIC_CLICINT_76
    4'b 1111, // index[ 79] CLIC_CLICINT_77
    4'b 1111, // index[ 80] CLIC_CLICINT_78
    4'b 1111, // index[ 81] CLIC_CLICINT_79
    4'b 1111, // index[ 82] CLIC_CLICINT_80
    4'b 1111, // index[ 83] CLIC_CLICINT_81
    4'b 1111, // index[ 84] CLIC_CLICINT_82
    4'b 1111, // index[ 85] CLIC_CLICINT_83
    4'b 1111, // index[ 86] CLIC_CLICINT_84
    4'b 1111, // index[ 87] CLIC_CLICINT_85
    4'b 1111, // index[ 88] CLIC_CLICINT_86
    4'b 1111, // index[ 89] CLIC_CLICINT_87
    4'b 1111, // index[ 90] CLIC_CLICINT_88
    4'b 1111, // index[ 91] CLIC_CLICINT_89
    4'b 1111, // index[ 92] CLIC_CLICINT_90
    4'b 1111, // index[ 93] CLIC_CLICINT_91
    4'b 1111, // index[ 94] CLIC_CLICINT_92
    4'b 1111, // index[ 95] CLIC_CLICINT_93
    4'b 1111, // index[ 96] CLIC_CLICINT_94
    4'b 1111, // index[ 97] CLIC_CLICINT_95
    4'b 1111, // index[ 98] CLIC_CLICINT_96
    4'b 1111, // index[ 99] CLIC_CLICINT_97
    4'b 1111, // index[100] CLIC_CLICINT_98
    4'b 1111, // index[101] CLIC_CLICINT_99
    4'b 1111, // index[102] CLIC_CLICINT_100
    4'b 1111, // index[103] CLIC_CLICINT_101
    4'b 1111, // index[104] CLIC_CLICINT_102
    4'b 1111, // index[105] CLIC_CLICINT_103
    4'b 1111, // index[106] CLIC_CLICINT_104
    4'b 1111, // index[107] CLIC_CLICINT_105
    4'b 1111, // index[108] CLIC_CLICINT_106
    4'b 1111, // index[109] CLIC_CLICINT_107
    4'b 1111, // index[110] CLIC_CLICINT_108
    4'b 1111, // index[111] CLIC_CLICINT_109
    4'b 1111, // index[112] CLIC_CLICINT_110
    4'b 1111, // index[113] CLIC_CLICINT_111
    4'b 1111, // index[114] CLIC_CLICINT_112
    4'b 1111, // index[115] CLIC_CLICINT_113
    4'b 1111, // index[116] CLIC_CLICINT_114
    4'b 1111, // index[117] CLIC_CLICINT_115
    4'b 1111, // index[118] CLIC_CLICINT_116
    4'b 1111, // index[119] CLIC_CLICINT_117
    4'b 1111, // index[120] CLIC_CLICINT_118
    4'b 1111, // index[121] CLIC_CLICINT_119
    4'b 1111, // index[122] CLIC_CLICINT_120
    4'b 1111, // index[123] CLIC_CLICINT_121
    4'b 1111, // index[124] CLIC_CLICINT_122
    4'b 1111, // index[125] CLIC_CLICINT_123
    4'b 1111, // index[126] CLIC_CLICINT_124
    4'b 1111, // index[127] CLIC_CLICINT_125
    4'b 1111, // index[128] CLIC_CLICINT_126
    4'b 1111, // index[129] CLIC_CLICINT_127
    4'b 1111, // index[130] CLIC_CLICINT_128
    4'b 1111, // index[131] CLIC_CLICINT_129
    4'b 1111, // index[132] CLIC_CLICINT_130
    4'b 1111, // index[133] CLIC_CLICINT_131
    4'b 1111, // index[134] CLIC_CLICINT_132
    4'b 1111, // index[135] CLIC_CLICINT_133
    4'b 1111, // index[136] CLIC_CLICINT_134
    4'b 1111, // index[137] CLIC_CLICINT_135
    4'b 1111, // index[138] CLIC_CLICINT_136
    4'b 1111, // index[139] CLIC_CLICINT_137
    4'b 1111, // index[140] CLIC_CLICINT_138
    4'b 1111, // index[141] CLIC_CLICINT_139
    4'b 1111, // index[142] CLIC_CLICINT_140
    4'b 1111, // index[143] CLIC_CLICINT_141
    4'b 1111, // index[144] CLIC_CLICINT_142
    4'b 1111, // index[145] CLIC_CLICINT_143
    4'b 1111, // index[146] CLIC_CLICINT_144
    4'b 1111, // index[147] CLIC_CLICINT_145
    4'b 1111, // index[148] CLIC_CLICINT_146
    4'b 1111, // index[149] CLIC_CLICINT_147
    4'b 1111, // index[150] CLIC_CLICINT_148
    4'b 1111, // index[151] CLIC_CLICINT_149
    4'b 1111, // index[152] CLIC_CLICINT_150
    4'b 1111, // index[153] CLIC_CLICINT_151
    4'b 1111, // index[154] CLIC_CLICINT_152
    4'b 1111, // index[155] CLIC_CLICINT_153
    4'b 1111, // index[156] CLIC_CLICINT_154
    4'b 1111, // index[157] CLIC_CLICINT_155
    4'b 1111, // index[158] CLIC_CLICINT_156
    4'b 1111, // index[159] CLIC_CLICINT_157
    4'b 1111, // index[160] CLIC_CLICINT_158
    4'b 1111, // index[161] CLIC_CLICINT_159
    4'b 1111, // index[162] CLIC_CLICINT_160
    4'b 1111, // index[163] CLIC_CLICINT_161
    4'b 1111, // index[164] CLIC_CLICINT_162
    4'b 1111, // index[165] CLIC_CLICINT_163
    4'b 1111, // index[166] CLIC_CLICINT_164
    4'b 1111, // index[167] CLIC_CLICINT_165
    4'b 1111, // index[168] CLIC_CLICINT_166
    4'b 1111, // index[169] CLIC_CLICINT_167
    4'b 1111, // index[170] CLIC_CLICINT_168
    4'b 1111, // index[171] CLIC_CLICINT_169
    4'b 1111, // index[172] CLIC_CLICINT_170
    4'b 1111, // index[173] CLIC_CLICINT_171
    4'b 1111, // index[174] CLIC_CLICINT_172
    4'b 1111, // index[175] CLIC_CLICINT_173
    4'b 1111, // index[176] CLIC_CLICINT_174
    4'b 1111, // index[177] CLIC_CLICINT_175
    4'b 1111, // index[178] CLIC_CLICINT_176
    4'b 1111, // index[179] CLIC_CLICINT_177
    4'b 1111, // index[180] CLIC_CLICINT_178
    4'b 1111, // index[181] CLIC_CLICINT_179
    4'b 1111, // index[182] CLIC_CLICINT_180
    4'b 1111, // index[183] CLIC_CLICINT_181
    4'b 1111, // index[184] CLIC_CLICINT_182
    4'b 1111, // index[185] CLIC_CLICINT_183
    4'b 1111, // index[186] CLIC_CLICINT_184
    4'b 1111, // index[187] CLIC_CLICINT_185
    4'b 1111, // index[188] CLIC_CLICINT_186
    4'b 1111, // index[189] CLIC_CLICINT_187
    4'b 1111, // index[190] CLIC_CLICINT_188
    4'b 1111, // index[191] CLIC_CLICINT_189
    4'b 1111, // index[192] CLIC_CLICINT_190
    4'b 1111, // index[193] CLIC_CLICINT_191
    4'b 1111, // index[194] CLIC_CLICINT_192
    4'b 1111, // index[195] CLIC_CLICINT_193
    4'b 1111, // index[196] CLIC_CLICINT_194
    4'b 1111, // index[197] CLIC_CLICINT_195
    4'b 1111, // index[198] CLIC_CLICINT_196
    4'b 1111, // index[199] CLIC_CLICINT_197
    4'b 1111, // index[200] CLIC_CLICINT_198
    4'b 1111, // index[201] CLIC_CLICINT_199
    4'b 1111, // index[202] CLIC_CLICINT_200
    4'b 1111, // index[203] CLIC_CLICINT_201
    4'b 1111, // index[204] CLIC_CLICINT_202
    4'b 1111, // index[205] CLIC_CLICINT_203
    4'b 1111, // index[206] CLIC_CLICINT_204
    4'b 1111, // index[207] CLIC_CLICINT_205
    4'b 1111, // index[208] CLIC_CLICINT_206
    4'b 1111, // index[209] CLIC_CLICINT_207
    4'b 1111, // index[210] CLIC_CLICINT_208
    4'b 1111, // index[211] CLIC_CLICINT_209
    4'b 1111, // index[212] CLIC_CLICINT_210
    4'b 1111, // index[213] CLIC_CLICINT_211
    4'b 1111, // index[214] CLIC_CLICINT_212
    4'b 1111, // index[215] CLIC_CLICINT_213
    4'b 1111, // index[216] CLIC_CLICINT_214
    4'b 1111, // index[217] CLIC_CLICINT_215
    4'b 1111, // index[218] CLIC_CLICINT_216
    4'b 1111, // index[219] CLIC_CLICINT_217
    4'b 1111, // index[220] CLIC_CLICINT_218
    4'b 1111, // index[221] CLIC_CLICINT_219
    4'b 1111, // index[222] CLIC_CLICINT_220
    4'b 1111, // index[223] CLIC_CLICINT_221
    4'b 1111, // index[224] CLIC_CLICINT_222
    4'b 1111, // index[225] CLIC_CLICINT_223
    4'b 1111, // index[226] CLIC_CLICINT_224
    4'b 1111, // index[227] CLIC_CLICINT_225
    4'b 1111, // index[228] CLIC_CLICINT_226
    4'b 1111, // index[229] CLIC_CLICINT_227
    4'b 1111, // index[230] CLIC_CLICINT_228
    4'b 1111, // index[231] CLIC_CLICINT_229
    4'b 1111, // index[232] CLIC_CLICINT_230
    4'b 1111, // index[233] CLIC_CLICINT_231
    4'b 1111, // index[234] CLIC_CLICINT_232
    4'b 1111, // index[235] CLIC_CLICINT_233
    4'b 1111, // index[236] CLIC_CLICINT_234
    4'b 1111, // index[237] CLIC_CLICINT_235
    4'b 1111, // index[238] CLIC_CLICINT_236
    4'b 1111, // index[239] CLIC_CLICINT_237
    4'b 1111, // index[240] CLIC_CLICINT_238
    4'b 1111, // index[241] CLIC_CLICINT_239
    4'b 1111, // index[242] CLIC_CLICINT_240
    4'b 1111, // index[243] CLIC_CLICINT_241
    4'b 1111, // index[244] CLIC_CLICINT_242
    4'b 1111, // index[245] CLIC_CLICINT_243
    4'b 1111, // index[246] CLIC_CLICINT_244
    4'b 1111, // index[247] CLIC_CLICINT_245
    4'b 1111, // index[248] CLIC_CLICINT_246
    4'b 1111, // index[249] CLIC_CLICINT_247
    4'b 1111, // index[250] CLIC_CLICINT_248
    4'b 1111, // index[251] CLIC_CLICINT_249
    4'b 1111, // index[252] CLIC_CLICINT_250
    4'b 1111, // index[253] CLIC_CLICINT_251
    4'b 1111, // index[254] CLIC_CLICINT_252
    4'b 1111, // index[255] CLIC_CLICINT_253
    4'b 1111, // index[256] CLIC_CLICINT_254
    4'b 1111  // index[257] CLIC_CLICINT_255
  };

endpackage

