// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package clicvs_reg_pkg;

    localparam CLICVS_REG_DATA_WIDTH = 32;
    localparam CLICVS_REG_MIN_ADDR_WIDTH = 3;
    localparam CLICVS_REG_SIZE = 'h4;

    typedef struct {
        logic value;
    } vsprio_t__prio0__out_t;

    typedef struct {
        logic value;
    } vsprio_t__prio1__out_t;

    typedef struct {
        logic value;
    } vsprio_t__prio2__out_t;

    typedef struct {
        logic value;
    } vsprio_t__prio3__out_t;

    typedef struct {
        vsprio_t__prio0__out_t prio0;
        vsprio_t__prio1__out_t prio1;
        vsprio_t__prio2__out_t prio2;
        vsprio_t__prio3__out_t prio3;
    } vsprio_t__out_t;

    typedef struct {
        vsprio_t__out_t vsprio;
    } clicvs__out_t;
endpackage
