// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package cliccfg_reg_pkg;

    localparam CLICCFG_REG_DATA_WIDTH = 32;
    localparam CLICCFG_REG_MIN_ADDR_WIDTH = 3;
    localparam CLICCFG_REG_SIZE = 'h4;

    typedef struct {
        logic [3:0] value;
    } cliccfg_t__mnlbits__out_t;

    typedef struct {
        logic [1:0] value;
    } cliccfg_t__nmbits__out_t;

    typedef struct {
        logic [3:0] value;
    } cliccfg_t__snlbits__out_t;

    typedef struct {
        logic [3:0] value;
    } cliccfg_t__unlbits__out_t;

    typedef struct {
        cliccfg_t__mnlbits__out_t mnlbits;
        cliccfg_t__nmbits__out_t nmbits;
        cliccfg_t__snlbits__out_t snlbits;
        cliccfg_t__unlbits__out_t unlbits;
    } cliccfg_t__out_t;

    typedef struct {
        cliccfg_t__out_t cliccfg;
    } cliccfg__out_t;
endpackage
