// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module clicint_reg (
        input wire clk,
        input wire arst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [2:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input clicint_reg_pkg::clicint__in_t hwif_in,
        output clicint_reg_pkg::clicint__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [2:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[2:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic clicint;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [2:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.clicint = cpuif_req_masked & (cpuif_addr == 3'h0);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } ip;
            struct {
                logic next;
                logic load_next;
            } ie;
            struct {
                logic next;
                logic load_next;
            } attr_shv;
            struct {
                logic [1:0] next;
                logic load_next;
            } attr_trig;
            struct {
                logic [1:0] next;
                logic load_next;
            } attr_mode;
            struct {
                logic [7:0] next;
                logic load_next;
            } ctl;
        } clicint;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } ip;
            struct {
                logic value;
            } ie;
            struct {
                logic value;
            } attr_shv;
            struct {
                logic [1:0] value;
            } attr_trig;
            struct {
                logic [1:0] value;
            } attr_mode;
            struct {
                logic [7:0] value;
            } ctl;
        } clicint;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: clicint.clicint.ip
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicint.ip.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicint && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicint.ip.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else if(hwif_in.clicint.ip.we) begin // HW Write - we
            next_c = hwif_in.clicint.ip.next;
            load_next_c = '1;
        end
        field_combo.clicint.ip.next = next_c;
        field_combo.clicint.ip.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicint.ip.value <= 1'h0;
        end else begin
            if(field_combo.clicint.ip.load_next) begin
                field_storage.clicint.ip.value <= field_combo.clicint.ip.next;
            end
        end
    end
    assign hwif_out.clicint.ip.value = field_storage.clicint.ip.value;
    // Field: clicint.clicint.ie
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicint.ie.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicint && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicint.ie.value & ~decoded_wr_biten[8:8]) | (decoded_wr_data[8:8] & decoded_wr_biten[8:8]);
            load_next_c = '1;
        end
        field_combo.clicint.ie.next = next_c;
        field_combo.clicint.ie.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicint.ie.value <= 1'h0;
        end else begin
            if(field_combo.clicint.ie.load_next) begin
                field_storage.clicint.ie.value <= field_combo.clicint.ie.next;
            end
        end
    end
    assign hwif_out.clicint.ie.value = field_storage.clicint.ie.value;
    // Field: clicint.clicint.attr_shv
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicint.attr_shv.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicint && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicint.attr_shv.value & ~decoded_wr_biten[16:16]) | (decoded_wr_data[16:16] & decoded_wr_biten[16:16]);
            load_next_c = '1;
        end
        field_combo.clicint.attr_shv.next = next_c;
        field_combo.clicint.attr_shv.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicint.attr_shv.value <= 1'h0;
        end else begin
            if(field_combo.clicint.attr_shv.load_next) begin
                field_storage.clicint.attr_shv.value <= field_combo.clicint.attr_shv.next;
            end
        end
    end
    assign hwif_out.clicint.attr_shv.value = field_storage.clicint.attr_shv.value;
    // Field: clicint.clicint.attr_trig
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicint.attr_trig.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicint && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicint.attr_trig.value & ~decoded_wr_biten[18:17]) | (decoded_wr_data[18:17] & decoded_wr_biten[18:17]);
            load_next_c = '1;
        end
        field_combo.clicint.attr_trig.next = next_c;
        field_combo.clicint.attr_trig.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicint.attr_trig.value <= 2'h0;
        end else begin
            if(field_combo.clicint.attr_trig.load_next) begin
                field_storage.clicint.attr_trig.value <= field_combo.clicint.attr_trig.next;
            end
        end
    end
    assign hwif_out.clicint.attr_trig.value = field_storage.clicint.attr_trig.value;
    // Field: clicint.clicint.attr_mode
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicint.attr_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicint && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicint.attr_mode.value & ~decoded_wr_biten[23:22]) | (decoded_wr_data[23:22] & decoded_wr_biten[23:22]);
            load_next_c = '1;
        end
        field_combo.clicint.attr_mode.next = next_c;
        field_combo.clicint.attr_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicint.attr_mode.value <= 2'h3;
        end else begin
            if(field_combo.clicint.attr_mode.load_next) begin
                field_storage.clicint.attr_mode.value <= field_combo.clicint.attr_mode.next;
            end
        end
    end
    assign hwif_out.clicint.attr_mode.value = field_storage.clicint.attr_mode.value;
    // Field: clicint.clicint.ctl
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.clicint.ctl.value;
        load_next_c = '0;
        if(decoded_reg_strb.clicint && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.clicint.ctl.value & ~decoded_wr_biten[31:24]) | (decoded_wr_data[31:24] & decoded_wr_biten[31:24]);
            load_next_c = '1;
        end
        field_combo.clicint.ctl.next = next_c;
        field_combo.clicint.ctl.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.clicint.ctl.value <= 8'h0;
        end else begin
            if(field_combo.clicint.ctl.load_next) begin
                field_storage.clicint.ctl.value <= field_combo.clicint.ctl.next;
            end
        end
    end
    assign hwif_out.clicint.ctl.value = field_storage.clicint.ctl.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [2:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 3'h0) begin
            readback_data_var[0] = field_storage.clicint.ip.value;
            readback_data_var[8] = field_storage.clicint.ie.value;
            readback_data_var[16] = field_storage.clicint.attr_shv.value;
            readback_data_var[18:17] = field_storage.clicint.attr_trig.value;
            readback_data_var[23:22] = field_storage.clicint.attr_mode.value;
            readback_data_var[31:24] = field_storage.clicint.ctl.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
