// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package clicvs_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } prio0;
    struct packed {
      logic        q;
    } prio1;
    struct packed {
      logic        q;
    } prio2;
    struct packed {
      logic        q;
    } prio3;
  } clicvs_reg2hw_vsprio_reg_t;

  // Register -> HW type
  typedef struct packed {
    clicvs_reg2hw_vsprio_reg_t vsprio; // [3:0]
  } clicvs_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CLICVS_VSPRIO_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    CLICVS_VSPRIO
  } clicvs_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CLICVS_PERMIT [1] = '{
    4'b 1111  // index[0] CLICVS_VSPRIO
  };

endpackage

