// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module clicintv_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 2
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output clicintv_reg_pkg::clicintv_reg2hw_t reg2hw, // Write


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import clicintv_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic clicintv_v0_qs;
  logic clicintv_v0_wd;
  logic clicintv_v0_we;
  logic [5:0] clicintv_vsid0_qs;
  logic [5:0] clicintv_vsid0_wd;
  logic clicintv_vsid0_we;
  logic clicintv_v1_qs;
  logic clicintv_v1_wd;
  logic clicintv_v1_we;
  logic [5:0] clicintv_vsid1_qs;
  logic [5:0] clicintv_vsid1_wd;
  logic clicintv_vsid1_we;
  logic clicintv_v2_qs;
  logic clicintv_v2_wd;
  logic clicintv_v2_we;
  logic [5:0] clicintv_vsid2_qs;
  logic [5:0] clicintv_vsid2_wd;
  logic clicintv_vsid2_we;
  logic clicintv_v3_qs;
  logic clicintv_v3_wd;
  logic clicintv_v3_we;
  logic [5:0] clicintv_vsid3_qs;
  logic [5:0] clicintv_vsid3_wd;
  logic clicintv_vsid3_we;

  // Register instances
  // R[clicintv]: V(False)

  //   F[v0]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_clicintv_v0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_v0_we),
    .wd     (clicintv_v0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.v0.q ),

    // to register interface (read)
    .qs     (clicintv_v0_qs)
  );


  //   F[vsid0]: 7:2
  prim_subreg #(
    .DW      (6),
    .SWACCESS("RW"),
    .RESVAL  (6'h0)
  ) u_clicintv_vsid0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_vsid0_we),
    .wd     (clicintv_vsid0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.vsid0.q ),

    // to register interface (read)
    .qs     (clicintv_vsid0_qs)
  );


  //   F[v1]: 8:8
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_clicintv_v1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_v1_we),
    .wd     (clicintv_v1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.v1.q ),

    // to register interface (read)
    .qs     (clicintv_v1_qs)
  );


  //   F[vsid1]: 15:10
  prim_subreg #(
    .DW      (6),
    .SWACCESS("RW"),
    .RESVAL  (6'h0)
  ) u_clicintv_vsid1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_vsid1_we),
    .wd     (clicintv_vsid1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.vsid1.q ),

    // to register interface (read)
    .qs     (clicintv_vsid1_qs)
  );


  //   F[v2]: 16:16
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_clicintv_v2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_v2_we),
    .wd     (clicintv_v2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.v2.q ),

    // to register interface (read)
    .qs     (clicintv_v2_qs)
  );


  //   F[vsid2]: 23:18
  prim_subreg #(
    .DW      (6),
    .SWACCESS("RW"),
    .RESVAL  (6'h0)
  ) u_clicintv_vsid2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_vsid2_we),
    .wd     (clicintv_vsid2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.vsid2.q ),

    // to register interface (read)
    .qs     (clicintv_vsid2_qs)
  );


  //   F[v3]: 24:24
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_clicintv_v3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_v3_we),
    .wd     (clicintv_v3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.v3.q ),

    // to register interface (read)
    .qs     (clicintv_v3_qs)
  );


  //   F[vsid3]: 31:26
  prim_subreg #(
    .DW      (6),
    .SWACCESS("RW"),
    .RESVAL  (6'h0)
  ) u_clicintv_vsid3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (clicintv_vsid3_we),
    .wd     (clicintv_vsid3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.clicintv.vsid3.q ),

    // to register interface (read)
    .qs     (clicintv_vsid3_qs)
  );




  logic [0:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == CLICINTV_CLICINTV_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(CLICINTV_PERMIT[0] & ~reg_be)))));
  end

  assign clicintv_v0_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_v0_wd = reg_wdata[0];

  assign clicintv_vsid0_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_vsid0_wd = reg_wdata[7:2];

  assign clicintv_v1_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_v1_wd = reg_wdata[8];

  assign clicintv_vsid1_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_vsid1_wd = reg_wdata[15:10];

  assign clicintv_v2_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_v2_wd = reg_wdata[16];

  assign clicintv_vsid2_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_vsid2_wd = reg_wdata[23:18];

  assign clicintv_v3_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_v3_wd = reg_wdata[24];

  assign clicintv_vsid3_we = addr_hit[0] & reg_we & !reg_error;
  assign clicintv_vsid3_wd = reg_wdata[31:26];

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = clicintv_v0_qs;
        reg_rdata_next[7:2] = clicintv_vsid0_qs;
        reg_rdata_next[8] = clicintv_v1_qs;
        reg_rdata_next[15:10] = clicintv_vsid1_qs;
        reg_rdata_next[16] = clicintv_v2_qs;
        reg_rdata_next[23:18] = clicintv_vsid2_qs;
        reg_rdata_next[24] = clicintv_v3_qs;
        reg_rdata_next[31:26] = clicintv_vsid3_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module clicintv_reg_top_intf
#(
  parameter int AW = 2,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output clicintv_reg_pkg::clicintv_reg2hw_t reg2hw, // Write
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  clicintv_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .devmode_i
  );
  
endmodule


