// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package clicintv_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 0;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } v;
    struct packed {
      logic [5:0]  q;
    } vsid;
  } clicintv_reg2hw_clicintv_reg_t;

  // Register -> HW type
  typedef struct packed {
    clicintv_reg2hw_clicintv_reg_t clicintv; // [6:0]
  } clicintv_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] CLICINTV_CLICINTV_OFFSET = 0'h 0;

  // Register index
  typedef enum int {
    CLICINTV_CLICINTV
  } clicintv_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] CLICINTV_PERMIT [1] = '{
    4'b 0001  // index[0] CLICINTV_CLICINTV
  };

endpackage

