// Copyright 2026 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package clicintv_reg_pkg;

    localparam CLICINTV_REG_DATA_WIDTH = 32;
    localparam CLICINTV_REG_MIN_ADDR_WIDTH = 3;
    localparam CLICINTV_REG_SIZE = 'h4;

    typedef struct {
        logic value;
    } clicintv_t__v0__out_t;

    typedef struct {
        logic [5:0] value;
    } clicintv_t__vsid0__out_t;

    typedef struct {
        logic value;
    } clicintv_t__v1__out_t;

    typedef struct {
        logic [5:0] value;
    } clicintv_t__vsid1__out_t;

    typedef struct {
        logic value;
    } clicintv_t__v2__out_t;

    typedef struct {
        logic [5:0] value;
    } clicintv_t__vsid2__out_t;

    typedef struct {
        logic value;
    } clicintv_t__v3__out_t;

    typedef struct {
        logic [5:0] value;
    } clicintv_t__vsid3__out_t;

    typedef struct {
        clicintv_t__v0__out_t v0;
        clicintv_t__vsid0__out_t vsid0;
        clicintv_t__v1__out_t v1;
        clicintv_t__vsid1__out_t vsid1;
        clicintv_t__v2__out_t v2;
        clicintv_t__vsid2__out_t vsid2;
        clicintv_t__v3__out_t v3;
        clicintv_t__vsid3__out_t vsid3;
    } clicintv_t__out_t;

    typedef struct {
        clicintv_t__out_t clicintv;
    } clicintv__out_t;
endpackage
