// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package mclic_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 2;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
    } mnlbits;
    struct packed {
      logic [1:0]  q;
    } nmbits;
    struct packed {
      logic [3:0]  q;
    } snlbits;
    struct packed {
      logic [3:0]  q;
    } unlbits;
  } mclic_reg2hw_mcliccfg_reg_t;

  // Register -> HW type
  typedef struct packed {
    mclic_reg2hw_mcliccfg_reg_t mcliccfg; // [13:0]
  } mclic_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] MCLIC_MCLICCFG_OFFSET = 2'h 0;

  // Register index
  typedef enum int {
    MCLIC_MCLICCFG
  } mclic_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MCLIC_PERMIT [1] = '{
    4'b 1111  // index[0] MCLIC_MCLICCFG
  };

endpackage

