// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package mclic_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 3;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic [3:0]  q;
    } mnlbits;
    struct packed {
      logic [1:0]  q;
    } nmbits;
    struct packed {
      logic [3:0]  q;
    } snlbits;
    struct packed {
      logic [3:0]  q;
    } unlbits;
  } mclic_reg2hw_mcliccfg_reg_t;

  typedef struct packed {
    logic        q;
  } mclic_reg2hw_clicmnxticonf_reg_t;

  // Register -> HW type
  typedef struct packed {
    mclic_reg2hw_mcliccfg_reg_t mcliccfg; // [14:1]
    mclic_reg2hw_clicmnxticonf_reg_t clicmnxticonf; // [0:0]
  } mclic_reg2hw_t;

  // Register offsets
  parameter logic [BlockAw-1:0] MCLIC_MCLICCFG_OFFSET = 3'h 0;
  parameter logic [BlockAw-1:0] MCLIC_CLICMNXTICONF_OFFSET = 3'h 4;

  // Register index
  typedef enum int {
    MCLIC_MCLICCFG,
    MCLIC_CLICMNXTICONF
  } mclic_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] MCLIC_PERMIT [2] = '{
    4'b 1111, // index[0] MCLIC_MCLICCFG
    4'b 0001  // index[1] MCLIC_CLICMNXTICONF
  };

endpackage

